services:
  wireCalc:
    image: wirecalc.server
    container_name: wireCalc
    build:
      context: .
      dockerfile: Server/Dockerfile
      
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
